export const ACTIONS = {
  DROPDOWN: "DROPDOWN",
  DRAWER: "DRAWER",
  TOOLTIP: "TOOLTIP",
} as const;

export const ACTION_TYPES = {
  TOGGLE_DROPDOWN: "TOGGLE_DROPDOWN",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  TOGGLE_TOOLTIP: "TOGGLE_TOOLTIP",
  CLOSE_DROPDOWN: "CLOSE_DROPDOWN",
  CLOSE_DRAWER: "CLOSE_DRAWER",
  CLOSE_TOOLTIP: "CLOSE_TOOLTIP",
  CLOSE_ALL_OVERLAYS: "CLOSE_ALL_OVERLAYS",
} as const;
