export const ACTIONS = {
  DELETE_CHAT_MODAL: "DELETE_CHAT_MODAL",
  DELETE_CONVERSATION_MODAL: "DELETE_CONVERSATION_MODAL",
} as const;

export const ACTION_TYPES = {
  TOGGLE_DELETE_CHAT_MODAL: "TOGGLE_DELETE_CHAT_MODAL",
  TOGGLE_DELETE_CONVERSATION_MODAL: "TOGGLE_DELETE_CONVERSATION_MODAL",
  DELETE_CHAT_CONFIRMATION: "DELETE_CHAT_CONFIRMATION",
  DELETE_CONVERSATION_CONFIRMATION: "DELETE_CONVERSATION_CONFIRMATION",
  TOGGLE_CHAT_DROPDOWN: "TOGGLE_CHAT_DROPDOWN",
} as const;
