export const ACTIONS = {
  EDIT_MESSAGE_MODAL: "EDIT_MESSAGE_MODAL",
  DELETE_MESSAGE_MODAL: "DELETE_MESSAGE_MODAL",
} as const;

export const ACTION_TYPES = {
  TOGGLE_EDIT_MESSAGE_MODAL: "TOGGLE_EDIT_MESSAGE_MODAL",
  TOGGLE_DELETE_MESSAGE_MODAL: "TOGGLE_DELETE_MESSAGE_MODAL",
  EDIT_MESSAGE_CONFIRMATION: "EDIT_MESSAGE_CONFIRMATION",
  DELETE_MESSAGE_CONFIRMATION: "DELETE_MESSAGE_CONFIRMATION",
  COPY_MESSAGE: "COPY_MESSAGE",
  TOGGLE_MESSAGE_DROPDOWN: "TOGGLE_MESSAGE_DROPDOWN",
} as const;
