export const ACTIONS = {
  DELETE_MESSAGE_MODAL: "DELETE_MESSAGE_MODAL",
  EDIT_MESSAGE_MODAL: "EDIT_MESSAGE_MODAL",
} as const;

export const ACTION_TYPES = {
  TOGGLE_DELETE_MESSAGE_MODAL: "TOGGLE_DELETE_MESSAGE_MODAL",
  TOGGLE_EDIT_MESSAGE_MODAL: "TOGGLE_EDIT_MESSAGE_MODAL",
  CLOSE_DELETE_MESSAGE_MODAL: "CLOSE_DELETE_MESSAGE_MODAL",
  CLOSE_EDIT_MESSAGE_MODAL: "CLOSE_EDIT_MESSAGE_MODAL",
  DELETE_MESSAGE_CONFIRMATION: "DELETE_MESSAGE_CONFIRMATION",
  EDIT_MESSAGE_CONFIRMATION: "EDIT_MESSAGE_CONFIRMATION",
} as const;
